window.completions = [
  { rank: 1, victors: ["inter"], name: "Tower of Rezz Oant", difficulty: 12.05 },
  { rank: 2, victors: ["Zenythal"], name: "Tower of Reproachful Eyewall", difficulty: 11.66 },
  { rank: 3, victors: ["inter"], name: "Tower of Unpremeditated Paraphernalia", difficulty: 11.62 },
  { rank: 4, victors: ["inter"], name: "Tower of Beast Weaver", difficulty: 11.37 },
  { rank: 5, victors: ["Zenythal","inter"], name: "Tower of Generation Failure", difficulty: 11.11 },
  { rank: 6, victors: ["Zenythal","H1nored"], name: "Tower of Widly Wacky Wonders", difficulty: 10.75 },
  { rank: 7, victors: ["inter"], name: "Tower of Cruel Underestimated Parkour", difficulty: 10.69 },
  { rank: 8, victors: ["inter"], name: "Tower of Lime Skittle", difficulty: 10.66 },
  { rank: 9, victors: ["inter","Zenythal"], name: "Tower of Spiralling Fates: Super Nerf", difficulty: 10.44 },
  { rank: 10, victors: ["Zenythal","Jruriarte2019","inter"], name: "Tower of Alien Radiance", difficulty: 10.4 },
  { rank: 11, victors: ["inter"], name: "Tower of Russian Escapade", difficulty: 10.37 },
  { rank: 12, victors: ["Zenythal","inter","Blvkef"], name: "Tower of Quantum Quadrivium", difficulty: 10.31 },
  { rank: 13, victors: ["Zenythal","inter"], name: "Steeple of Polynomial-C", difficulty: 10.25 },
  { rank: 14, victors: ["inter"], name: "Tower of Greyscale", difficulty: 10.08 },
  { rank: 15, victors: ["Zenythal"], name: "Tower of Impossible Movement", difficulty: 10.05 },
  { rank: 16, victors: ["Zenythal","H1nored"], name: "Tower of Fractured Memories", difficulty: 10.00 },
  { rank: 17, victors: ["Zenythal","inter","Blvkef"], name: "Tower of Externalizing Insanity", difficulty: 9.95 },
  { rank: 18, victors: ["Zenythal"], name: "Tower of The Dripping Amalgam", difficulty: 9.58 },
  { rank: 19, victors: ["Blvkef"], name: "Tower of Frightening Nightmares", difficulty: 9.50 },
  { rank: 20, victors: ["Zenythal","inter","Blvkef","H1nored"], name: "Tower of Hopeless Hell", difficulty: 9.40 },
  { rank: 21, victors: ["Blvkef","Zenythal"], name: "Tower of Bloodthirsty Kenos", difficulty: 9.13 },
  { rank: 22, victors: ["Zenythal"], name: "Tower of Rough Endoplasmic Reticulum", difficulty: 8.99 },
  { rank: 23, victors: ["inter"], name: "Tower of Confusingly Curved Pole", difficulty: 9.05 },
  { rank: 24, victors: ["Zenythal","H1nored","Scourge"], name: "Tower of Astral Eclipse", difficulty: 8.93 },
  { rank: 25, victors: ["Zenythal","Blvkef"], name: "Tower of Hollow Reformations", difficulty: 8.67 },

  { rank: 26, victors: ["Zenythal"], name: "Tower of Enraging Advancement", difficulty: 8.63 },
  { rank: 27, victors: ["Zenythal","inter","Blvkef"], name: "Tower of Inevitable Failure", difficulty: 8.45 },
  { rank: 28, victors: ["Blvkef","Zenythal","inter","H1nored"], name: "Tower of Thinning Layers", difficulty: 8.4 },
  { rank: 29, victors: ["Scourge"], name: "Tower of Flattened Uprise", difficulty: 8.35 },
  { rank: 30, victors: ["Blvkef","Zenythal","inter"], name: "Tower of Unsettling Heights", difficulty: 8.22 },
  { rank: 31, victors: ["Zenythal"], name: "Tower of Bent Trauma", difficulty: 8.18 },
  { rank: 32, victors: ["Blvkef","Zenythal"], name: "Tower of High Adrenaline", difficulty: 8.13 },
  { rank: 33, victors: ["Blvkef","Zenythal","inter"], name: "Thanos Tower", difficulty: 8.13 },
  { rank: 34, victors: ["Blvkef","Zenythal","inter","Jruriarte2019"], name: "Tower of Vacant Hindrances: Super Nerf", difficulty: 8.1 },
  { rank: 35, victors: ["inter"], name: "Steeple of 35 Lodges of Hell", difficulty: 8.07 },
  { rank: 36, victors: ["Zenythal"], name: "Tower of Harsh Aesthetical Obstacles", difficulty: 8.02 },
  { rank: 37, victors: ["Blvkef","Zenythal","inter","H1nored"], name: "Tower of Difficulty Chart", difficulty: 8.02 },
  { rank: 38, victors: ["inter","Blvkef","Zenythal"], name: "Tower of 40 Jumps of Hell", difficulty: 8.01 },
  { rank: 39, victors: ["Zenythal","inter","Blvkef"], name: "Tower of Double Trouble", difficulty: 8.00 },
  { rank: 40, victors: ["Zenythal"], name: "Steeple of Esoteric Arcane", difficulty: 8.00 }
];
